/**
 * Style Dictionary 构建脚本（三端产物）
 * 用法：node sd.config.cjs
 */
const StyleDictionary = require("style-dictionary").default;
const fs = require("node:fs");
const path = require("node:path");

StyleDictionary.registerFormat({
  name: "scss/variables",
  format: ({ dictionary }) => {
    const lines = ["// Auto-generated by @boks/design-tokens. Do not edit."];
    const flat = {};
    for (const t of dictionary.allTokens) {
      const k = t.path.join("-").toLowerCase().replace(/\./g, "-");
      flat[k] = t.value;
      lines.push(`$${k}: ${t.value};`);
    }
    fs.writeFileSync(
      path.join(__dirname, "build/scss/_tokens.scss"),
      lines.join("\n") + "\n",
    );
  },
});

StyleDictionary.registerFormat({
  name: "css/variables",
  format: ({ dictionary }) => {
    const lines = [":root {"];
    for (const t of dictionary.allTokens) {
      const k = "--" + t.path.join("-").toLowerCase().replace(/\./g, "-");
      lines.push(`  ${k}: ${t.value};`);
    }
    lines.push("}");
    fs.writeFileSync(
      path.join(__dirname, "build/css/variables.css"),
      lines.join("\n") + "\n",
    );
  },
});

StyleDictionary.registerFormat({
  name: "javascript/module-flat",
  format: ({ dictionary }) => {
    const lines = [
      "// Auto-generated by @boks/design-tokens.",
      "export const tokens = {",
    ];
    const obj = {};
    for (const t of dictionary.allTokens) {
      const k = t.path.join("_").toUpperCase();
      obj[k] = t.value;
    }
    for (const [k, v] of Object.entries(obj)) {
      lines.push(`  ${k}: ${JSON.stringify(v)},`);
    }
    lines.push("};");
    fs.mkdirSync(path.join(__dirname, "build/ts"), { recursive: true });
    fs.writeFileSync(
      path.join(__dirname, "build/ts/tokens.js"),
      lines.join("\n") + "\n",
    );
    fs.writeFileSync(
      path.join(__dirname, "build/ts/tokens.d.ts"),
      "export declare const tokens: Readonly<Record<string, string>>;\n",
    );
  },
});

StyleDictionary.registerFormat({
  name: "dart/class",
  format: ({ dictionary }) => {
    const lines = [
      "// Auto-generated by @boks/design-tokens.",
      "class BoksTokens {",
    ];
    const all = {};
    for (const t of dictionary.allTokens) {
      const k = t.path.join("_").toUpperCase().replace(/-/g, "_");
      all[k] = t.value;
    }
    for (const [k, v] of Object.entries(all)) {
      lines.push(`  static const String ${k} = ${JSON.stringify(v)};`);
    }
    lines.push("}");
    fs.mkdirSync(path.join(__dirname, "build/dart"), { recursive: true });
    fs.writeFileSync(
      path.join(__dirname, "build/dart/boks_tokens.dart"),
      lines.join("\n") + "\n",
    );
  },
});

const sd = new StyleDictionary({
  source: ["tokens/**/*.json"],
  platforms: {
    scss: {
      transformGroup: "scss",
      buildPath: "build/",
      files: [{ destination: "_tokens.scss", format: "scss/variables" }],
    },
    css: {
      transformGroup: "css",
      buildPath: "build/",
      files: [{ destination: "variables.css", format: "css/variables" }],
    },
    js: {
      transformGroup: "js",
      buildPath: "build/",
      files: [{ destination: "tokens.js", format: "javascript/module-flat" }],
    },
    dart: {
      transformGroup: "js",
      buildPath: "build/",
      files: [{ destination: "boks_tokens.dart", format: "dart/class" }],
    },
  },
});

sd.buildAllPlatforms();
console.log("design-tokens built: scss / css / js / dart");
