export default defineAppConfig({
  pages: [
    "pages/home/index",
    "pages/family/index",
    "pages/assessment/start",
    "pages/assessment/input",
    "pages/report/list",
    "pages/report/detail",
    "pages/training/detail",
    "pages/posture/consent",
    "pages/posture/capture",
    "pages/posture/report",
    "pages/chat/index",
    "pages/privacy/index",
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#103E2F",
    navigationBarTitleText: "BOKS智能体测体态分析",
    navigationBarTextStyle: "white",
  },
  tabBar: {
    custom: true,
    color: "#5B7168",
    selectedColor: "#1F6E45",
    backgroundColor: "#FFFFFF",
    borderStyle: "white",
    list: [
      { pagePath: "pages/home/index", text: "首页" },
      { pagePath: "pages/assessment/start", text: "体测" },
      { pagePath: "pages/training/detail", text: "训练" },
      { pagePath: "pages/family/index", text: "我的" },
    ],
  },
});